'use client';
import { useState, useEffect } from 'react';
import AppLayout from '@/components/shared/AppLayout';
import { AuthProvider } from '@/hooks/useAuth';
import api from '@/lib/api';
import { useSearchParams } from 'next/navigation';
import { ChevronLeft, MapPin, Phone, Printer, CheckCircle } from 'lucide-react';
import Link from 'next/link';

function ReferralPage() {
  const searchParams = useSearchParams();
  const consultationId = searchParams.get('consultationId');
  const [referralTo, setReferralTo] = useState('District Hospital');
  const [notes, setNotes] = useState('');
  const [referral, setReferral] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [recentReferrals, setRecentReferrals] = useState<any[]>([]);

  useEffect(() => {
    if (!consultationId) {
      // Load recent referrals
      api.get('/patients?limit=5').catch(console.error);
    }
  }, [consultationId]);

  const generate = async () => {
    if (!consultationId) return;
    setLoading(true);
    try {
      const res = await api.post(`/referral/generate/${consultationId}`, { referralTo, notes });
      setReferral(res.data.referral);
    } catch (err: any) {
      alert(err.response?.data?.error || 'Failed to generate referral');
    } finally {
      setLoading(false);
    }
  };

  if (referral) {
    const { patient, consultation, facilities } = referral;
    const urgencyColor = {
      critical: 'border-red-500 bg-red-50',
      high: 'border-orange-400 bg-orange-50',
      medium: 'border-amber-400 bg-amber-50',
      low: 'border-green-400 bg-green-50'
    }[referral.urgency] || 'border-gray-300 bg-white';

    return (
      <div>
        <div className="page-header">
          <button onClick={() => setReferral(null)} className="text-white/80"><ChevronLeft size={24} /></button>
          <h1 className="text-lg font-bold font-display flex-1">Referral Slip</h1>
          <button className="bg-white/20 px-3 py-1.5 rounded-xl text-white text-xs font-semibold flex items-center gap-1">
            <Printer size={14} /> Print
          </button>
        </div>

        <div className="p-4 space-y-4 pb-8">
          <div className={`card border-2 ${urgencyColor} animate-fade-in-scale`}>
            <div className="flex items-center justify-between mb-3">
              <div>
                <p className="text-xs text-gray-500">Referral ID</p>
                <p className="font-bold text-gray-800 font-mono">{referral.referralId}</p>
              </div>
              <span className={`px-3 py-1 rounded-full text-xs font-bold uppercase ${referral.urgency === 'critical' ? 'bg-red-600 text-white' : referral.urgency === 'high' ? 'bg-orange-500 text-white' : 'bg-amber-400 text-white'}`}>
                {referral.urgency}
              </span>
            </div>

            <div className="border-t border-b border-gray-100 py-3 my-3 space-y-1">
              <h3 className="font-bold text-sm text-gray-600 uppercase tracking-wide">Patient</h3>
              <p className="font-bold text-gray-800 text-lg">{patient.name}</p>
              <p className="text-sm text-gray-600">{patient.age}y • {patient.gender} • {patient.village}</p>
              {patient.phone && <p className="text-sm text-gray-600">📞 {patient.phone}</p>}
              {patient.allergies && <p className="text-sm text-orange-600">⚠️ Allergies: {patient.allergies}</p>}
            </div>

            <div className="space-y-2">
              <h3 className="font-bold text-sm text-gray-600 uppercase tracking-wide">Diagnosis Summary</h3>
              {consultation.triageResult?.possibleConditions?.map((c: any, i: number) => (
                <div key={i} className="text-sm text-gray-700">• {c.name} ({Math.round(c.confidence * 100)}% confidence)</div>
              ))}
            </div>

            <div className="mt-3 pt-3 border-t border-gray-100">
              <p className="text-xs font-bold text-gray-600 uppercase">Referring To</p>
              <p className="font-semibold text-gray-800">{referral.referralTo}</p>
            </div>

            <div className="mt-3 pt-3 border-t border-gray-100">
              <p className="text-xs font-bold text-gray-600 uppercase mb-2">Instructions</p>
              <p className="text-sm text-gray-700 bg-white rounded-xl p-3 border">{referral.instructions}</p>
            </div>

            <div className="mt-3 pt-3 border-t border-gray-100 text-xs text-gray-400">
              <p>Generated by: {referral.referringWorker}</p>
              <p>{new Date(referral.generatedAt).toLocaleString('en-IN')}</p>
              <p className="mt-1 font-medium text-gray-500">GramHealth AI — Emergency: 108 | PHC: 104</p>
            </div>
          </div>

          {/* Nearest Facilities */}
          {facilities?.length > 0 && (
            <div className="card">
              <h3 className="font-bold text-gray-800 mb-3 font-display flex items-center gap-2">
                <MapPin size={16} className="text-green-600" /> Nearest Facilities
              </h3>
              {facilities.map((f: any, i: number) => (
                <div key={i} className="flex items-center gap-3 p-3 bg-gray-50 rounded-2xl mb-2">
                  <div className="w-10 h-10 bg-green-100 rounded-xl flex items-center justify-center">🏥</div>
                  <div className="flex-1">
                    <p className="font-semibold text-sm text-gray-800">{f.name}</p>
                    <p className="text-xs text-gray-500">{f.distance} • {f.available}</p>
                  </div>
                  <a href={`tel:${f.phone}`} className="bg-green-600 text-white w-9 h-9 rounded-xl flex items-center justify-center">
                    <Phone size={16} />
                  </a>
                </div>
              ))}
            </div>
          )}

          <Link href="/dashboard">
            <button className="btn-primary w-full">✅ Done — Back to Dashboard</button>
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div>
      <div className="page-header">
        <Link href="/dashboard" className="text-white/80"><ChevronLeft size={24} /></Link>
        <h1 className="text-lg font-bold font-display">Generate Referral</h1>
      </div>

      <div className="p-4 space-y-4">
        {!consultationId ? (
          <div className="text-center py-10">
            <div className="text-5xl mb-4">📋</div>
            <p className="text-gray-600 font-semibold">No consultation selected</p>
            <p className="text-gray-400 text-sm mt-1">Run a symptom check first to generate a referral</p>
            <Link href="/symptoms">
              <button className="btn-primary mt-4">Start Symptom Check</button>
            </Link>
          </div>
        ) : (
          <>
            <div className="card space-y-4">
              <h2 className="font-bold text-gray-800 font-display">Referral Details</h2>

              <div>
                <label className="label">Refer To</label>
                <div className="space-y-2">
                  {['Primary Health Center', 'Community Health Center', 'District Hospital', 'Medical College Hospital'].map(f => (
                    <button key={f} onClick={() => setReferralTo(f)}
                      className={`w-full text-left p-3 rounded-2xl border-2 transition-all text-sm font-medium ${referralTo === f ? 'border-green-500 bg-green-50 text-green-800' : 'border-gray-200 bg-white text-gray-700'}`}>
                      🏥 {f}
                    </button>
                  ))}
                </div>
              </div>

              <div>
                <label className="label">Additional Notes for Doctor</label>
                <textarea className="input-field" rows={3} placeholder="Any special instructions or observations..."
                  value={notes} onChange={e => setNotes(e.target.value)} />
              </div>
            </div>

            <button className="btn-danger w-full" onClick={generate} disabled={loading}>
              {loading ? '⏳ Generating...' : '📋 Generate Referral Slip'}
            </button>
          </>
        )}
      </div>
    </div>
  );
}

export default function ReferralPageWrapper() {
  return (
    <AuthProvider>
      <AppLayout>
        <ReferralPage />
      </AppLayout>
    </AuthProvider>
  );
}
